# Generated by Django 5.2.1 on 2025-06-01 21:51

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('HOUSE', 'House'), ('VILLA', 'Villa'), ('TOWNHOUSE', 'Townhouse'), ('LOFT', 'Loft'), ('STUDIO', 'Studio'), ('MANSION', 'Mansion'), ('CASTLE', 'Castle'), ('FARMHOUSE', 'Farmhouse'), ('RESORT', 'Resort'), ('CHALET', 'Chalet'), ('APARTMENT', 'Apartment'), ('TENT', 'Tent'), ('TREEHOUSE', 'Treehouse'), ('YURT', 'Yurt'), ('BOAT', 'Boat'), ('CARAVAN', 'Caravan'), ('TRAILER', 'Trailer'), ('SHACK', 'Shack'), ('HUT', 'Hut'), ('COTTAGE', 'Cottage'), ('BUNGALOW', 'Bungalow'), ('PENTHOUSE', 'Penthouse')], default='APARTMENT', help_text='Type of the listing, e.g., House, Villa, Apartment, etc.', max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('location_address', models.CharField(max_length=255)),
                ('allowable_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('number_of_bathrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('amenities', models.JSONField(blank=True, default=list, null=True)),
                ('available_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.user')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.user'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_guests', models.PositiveIntegerField(default=0, help_text='Number of guests for the booking.')),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.user')),
            ],
        ),
    ]
