# Generated by Django 5.2.3 on 2025-06-15 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password must be at least 8 characters long and contain a mix of letters, numbers, and special characters.', max_length=128, validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
