# Generated by Django 5.2.1 on 2025-07-12 18:23

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password must be at least 8 characters long and contain a mix of letters, numbers, and special characters.', max_length=128, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the payment transaction.', max_length=50, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_booking', to='listings.booking')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_payee', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_payer', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('payments', django.db.models.manager.Manager()),
            ],
        ),
    ]
