"""routers.py
# This file defines the routers for the travel listings application.
# It sets up the API endpoints for managing listings, users, bookings, and reviews.
#"""

from rest_framework.routers import DefaultRouter

from .views import BookingViewSet, ListingViewSet, ReviewViewSet, UserViewSet

# Create a router and register the viewsets with it
router = DefaultRouter()
router.register(r"listings", ListingViewSet, basename="listing")
router.register(r"users", UserViewSet, basename="user")
router.register(r"bookings", BookingViewSet, basename="booking")
router.register(r"reviews", ReviewViewSet, basename="review")
# The router will automatically generate the URL conf for the viewsets

# The urlpatterns variable will contain the URLs generated by the router
urlpatterns = router.urls
